[package]
name = "bevy_axon_derive"
version = "0.1.1"
edition = "2021"
description = "Proc macros for bevy_axon"
license = "MIT"
repository = "https://github.com/hailongz-dev/bevy_axon"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

