[package]
name = "serde_sbin"
version = "0.1.0"
edition = "2021"
description = "Serialize Binary"
license = "MIT"
repository = "https://github.com/hailongz-dev/bevy_axon"

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["rlib"]
